# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-07 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220607_1348'),
        ('accounts', '0004_auto_20220605_0932'),
    ]

    operations = [
    ]
